name: 'Get & Cache Dependencies'
description: 'Get the depedencies via NPM and cache them'
inputs:
  caching:
   description: 'Do you wish to cache the dependencies?'
   required: false
   default: 'true'
  outputs:
    used-cache:
      description: 'Was the cache used (outputs)?'
      value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      # Only cache dependencies if the user wants to
      if: inputs.caching == 'true'
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      # Run npm install if the cache was not hit or if the user does not want to cache
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "Was cache used: ${{ inputs.caching }}"
        echo "cache='${{ inputs.caching }}'" >> $GIHUB_OUTPUT
      shell: bash